---
title: "A3: Incarceration"
output: html_document
---

### Introduction

As a student in Seattle, which is the county seat of King County, Washington, I am interested in the prison population rate in King County, WA. Because policies or people's perceptions change over time, I'd like to know the historical peaks of prison population rate and varies in different races since 1990 in King County, WA. Since racial and sexual injustice and oppression are always intertwined, I am also curious if there is any possible hint on the relation or intersection of sexual and racial issues. Thus, I intend to analyze the data on male and female prison population rates, along with the race that has the highest prison population rate in each county. Unlike the prison population, for the jail population, I am more inclined to base my analysis on states and focus on the latest year. Geographic divisions perhaps suggest some kind of discriminatory, oppressive, or prejudicial geographic tendency, so I intend to see the geographical distribution of the total jail population across the U.S. and the corresponding race that has appeared most frequently as the race with the highest jail population rate. I expect to find some commonalities in the geographic distribution.

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

These will likely be calculated using your DPLYR skills, answering questions such as: 

- What is the average value of my variable across all the counties (in the current year)?
- Where is my variable the highest / lowest?
- How much has my variable change over the last N years?

Feel free to calculate and report values that you find relevant. Again, remember that the purpose is to think about how these measure of incarceration vary by race.

### The Dataset

* Vera Institute of Justice collected the data. Vera generated their data from two Bureau of Justice Statistics (BJS) data collections: the Census of Jails (COJ) and the Annual Survey of Jails (ASJ). They continued to update their data from COJ and ASJ. Vera created the data because they intended to provide county-level data that could satisfy the level of detail necessary to unpack the causes and consequences of incarceration in the United States. Research on incarceration had traditionally centered on state-level data, which was less sufficient in detailed research compared with county-level data
* There are 91,031 observations (rows) and 26 features (columns) in the first data set(rate data), and there are 153,811 observations (rows) and 28 features (columns) in the second data set(population data).
* Ethical questions or questions of power: Since Vera collected data from the Bureau of Justice Statistics (BJS), one thing to consider is to challenge the power/authority. The benefit of authority is comprehensiveness, as Vera was able to collect detailed data at the county level. However, the final statistics displayed by BJS perhaps has been through multiple "treatments". We have no way of knowing the details of the data from the county level to the final data in the Census of Jails (COJ) and the Annual Survey of Jails (ASJ), such as how they sorted, merged, and cropped outliers. These statistical institutions may be part of components of the matrix of domination, and thus they may stand for the dominated groups. Since there was data on different ethical groups and genders, which may involve some potential ethical or sexual inequalities and bias, we shall not assume that these observations and features are completely accurate and uncontroversial simply because they are collected from these authorities.
* Limitations: One limitation of this data is that these data sets only include results. They only provide final numbers such as the jail population rate or prison population. In order to better understand and analyze if there are some racial or sexual discriminations implied by the data sets, I think it would be more sufficient if they could also classify the data by reasons for incarcerations. Another limitation of this data is that there are only two categories of gender, whereas many people have gender identities other than male or female. Thus, the data involving gender may be inaccurate or over-generalized.

### Trends Over Time Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The first chart that you will create and include will show the trend over time of your variable/topic. Think carefully about what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Show more than one, but fewer than ~10 trends
  - This may mean showing the same measure for different locations or different racial groups. Think carefully about a meaningful comparison of locations (e.g., the top 10 counties in a state, top 10 states, etc.)
- You must have clear x and y axis labels
- The chart needs a clear title 
- You need a legend for your different line colors and a clear legend title

When we say "clear" or "human readable" titles and labels, that means that you should not just display the variable name.

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Variable Comparison Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The second chart that you will create and include will show how two different (continuous) variables are related to one another. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- You must have clear x and y axis labels
- The chart needs a clear title 
- If you choose to add a color encoding (not required), you need a legend for your different color and a clear legend title

### Map

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The last chart that you will create and include will show how a variable is distributed geographically. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Your map needs a title
- Your color scale needs a legend with a clear label
- Use a map based coordinate system to set the aspect ratio of your map

